### ISSUE TITLE
Shifter

### ISSUE THREAD

**Issue by luki343** [grzezzz/BMWShifter#1]
Hey,
I had question about shifter (from f30), after connecting 12V to pin 10 (main power) and 7 (wakeup), and GND to pin 8, it should start sending CAN messages on one of the canbus? or is it waiting for some "wakeup" message? 

I connected it to arduino with your code hoping it would atleast light up but nothing... Maybe shifter is dead?

**Comment by awaisa123** [comment]
Hi I’ve got the same issue was it the shifter or something else
